name: Run Tennis Court Reservation Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '1 23 * * 3'
    - cron: '1 22 * * 3'

jobs:
  run-reservation-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        id: bot-run
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python -u "Book a Court.py"

      - name: Upload Screenshot Artifact
        if: failure() # <-- GEWIJZIGD/VEREENVOUDIGD
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: fatal_error.png
