name: Run Tennis Court Reservation Bot

on:
  workflow_dispatch:
  schedule:
    # Runs at 23:01 UTC on Thursday (00:01 CET Friday in NL - Winter)
    - cron: '1 23 * * 4'
    
    # Runs at 22:01 UTC on Thursday (00:01 CEST Friday in NL - Summer)
    - cron: '1 22 * * 4'

jobs:
  run-reservation-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        id: bot-run
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python -u "Book a Court.py"

      - name: Upload Failure Screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: fatal_error.png

      - name: Upload Success Screenshot
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: success-screenshot
          path: success_screenshot.png
