name: Run Tennis Court Reservation Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '1 23 * * 3'
    - cron: '1 22 * * 3'

jobs:
  run-reservation-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        id: bot-run # Geef de stap een ID
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python -u "Book a Court.py"

      # ✨ --- NIEUWE STAP: Upload de screenshot als deze bestaat --- ✨
      - name: Upload Screenshot Artifact
        if: failure() && steps.bot-run.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png
      # --- EINDE NIEUWE STAP ---
