name: Run Tennis Court Reservation Bot

on:
  workflow_dispatch: # Allows you to run the job manually from the Actions tab
  schedule:
    # Schedule 1: For Dutch Winter Time (CET, UTC+1)
    # Runs at 23:01 UTC on Wednesday, which is 00:01 CET on Thursday in the Netherlands.
    - cron: '1 23 * * 3'
    
    # Schedule 2: For Dutch Summer Time (CEST, UTC+2)
    # Runs at 22:01 UTC on Wednesday, which is 00:01 CEST on Thursday in the Netherlands.
    - cron: '1 22 * * 3'

jobs:
  run-reservation-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          # Use the secrets you configured in your repository settings
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python "Book a Court.py"
